# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Set library preference based on BUILD_SHARED_LIBS
#
if( BUILD_SHARED_LIBS)
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

#
# Generated from sourcetree: A3ED849C-ECFE-4FB8-8E50-D5245D67E30B;mulle-c11;no-all-load,no-cmake-inherit,no-import,no-link,no-recurse,no-singlephase;mulle-core,mulle-c11
# Disable with : `mulle-sourcetree mark mulle-c11 no-header`
# Disable for this platform: `mulle-sourcetree mark mulle-c11 no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-c11 no-cmake-sdk-<name>`
#
foreach( _TMP_MULLE__C11_HEADER_TARGET_TARGET mulle-core mulle-c11)
   if( TARGET ${_TMP_MULLE__C11_HEADER_TARGET_TARGET})
      set( MULLE__C11_HEADER_TARGET ${_TMP_MULLE__C11_HEADER_TARGET_TARGET})
      break()
   endif()
endforeach()
if( NOT MULLE__C11_HEADER AND NOT MULLE__C11_HEADER_TARGET)
   find_file( MULLE__C11_HEADER NAMES
      mulle-c11.h mulle-core/mulle-core.h mulle-c11/mulle-c11.h
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
   )
   if( NOT MULLE__C11_HEADER AND NOT DEPENDENCY_IGNORE_SYSTEM_HEADERS)
      find_file( MULLE__C11_HEADER NAMES
         mulle-c11.h mulle-core/mulle-core.h mulle-c11/mulle-c11.h
      )
   endif()
   message( STATUS "MULLE__C11_HEADER is ${MULLE__C11_HEADER}")

   #
   # Add MULLE__C11_HEADER to HEADER_ONLY_LIBRARIES list.
   # Disable with: `mulle-sourcetree mark mulle-c11 no-cmake-add`
   #
   set( HEADER_ONLY_LIBRARIES
      ${MULLE__C11_HEADER}
      ${HEADER_ONLY_LIBRARIES}
   )
   if( MULLE__C11_HEADER)
      # intentionally left blank
   else()
      # Disable with: `mulle-sourcetree mark mulle-c11 no-require`
      message( SEND_ERROR "MULLE__C11_HEADER was not found in mulle-c11.h mulle-core/mulle-core.h mulle-c11/mulle-c11.h")
   endif()
endif()



#
# Generated from sourcetree: 8D2BE61C-D741-4FCC-8A99-5EB39BBE7A3E;dlfcn-win32;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import,only-platform-mingw,only-platform-windows;mulle-core,dl
# Disable with : `mulle-sourcetree mark dlfcn-win32 no-link`
# Disable for this platform: `mulle-sourcetree mark dlfcn-win32 no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark dlfcn-win32 no-cmake-sdk-<name>`
#
if( ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
      list( APPEND DEPENDENCY_LIBRARIES "mulle-core")
   else()
      if( NOT DLFCN__WIN32_LIBRARY)
         foreach( _TMP_DLFCN__WIN32_LIBRARY_TARGET mulle-core dl)
            if( TARGET ${_TMP_DLFCN__WIN32_LIBRARY_TARGET})
               set( DLFCN__WIN32_LIBRARY ${_TMP_DLFCN__WIN32_LIBRARY_TARGET})
               break()
            endif()
         endforeach()
         if( NOT DLFCN__WIN32_LIBRARY)
            find_library( DLFCN__WIN32_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-core
               ${MULLE_PREFERRED_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}dl${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}dl${MULLE_FALLBACK_LIBRARY_SUFFIX}
               dl
               NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
            )
            if( NOT DLFCN__WIN32_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
               find_library( DLFCN__WIN32_LIBRARY NAMES
                  ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
                  ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
                  ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
                  ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
                  mulle-core
                  ${MULLE_PREFERRED_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
                  ${MULLE_PREFERRED_LIBRARY_PREFIX}dl${MULLE_PREFERRED_LIBRARY_SUFFIX}
                  ${MULLE_FALLBACK_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
                  ${MULLE_FALLBACK_LIBRARY_PREFIX}dl${MULLE_FALLBACK_LIBRARY_SUFFIX}
                  dl
               )
            endif()
         endif()
         message( STATUS "DLFCN__WIN32_LIBRARY is ${DLFCN__WIN32_LIBRARY}")
      endif()
      if( DLFCN__WIN32_LIBRARY)
            #
            # Add DLFCN__WIN32_LIBRARY to DEPENDENCY_LIBRARIES list.
            # Disable with: `mulle-sourcetree mark dlfcn-win32 no-cmake-add`
            #
            if( NOT ${DLFCN__WIN32_LIBRARY} IN_LIST DEPENDENCY_LIBRARIES)
               list( APPEND DEPENDENCY_LIBRARIES ${DLFCN__WIN32_LIBRARY})
            endif()
            #
            # Inherit information from dependency.
            # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
            # Disable with: `mulle-sourcetree mark dlfcn-win32 no-cmake-inherit`
            #
            # temporarily expand CMAKE_MODULE_PATH
            get_filename_component( _TMP_DLFCN__WIN32_ROOT "${DLFCN__WIN32_LIBRARY}" DIRECTORY)
            get_filename_component( _TMP_DLFCN__WIN32_ROOT "${_TMP_DLFCN__WIN32_ROOT}" DIRECTORY)
            #
            #
            # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
            # Disable with: `mulle-sourcetree mark dlfcn-win32 no-cmake-dependency`
            #
            foreach( _TMP_DLFCN__WIN32_NAME "mulle-core" "dl")
               set( _TMP_DLFCN__WIN32_DIR "${_TMP_DLFCN__WIN32_ROOT}/include/${_TMP_DLFCN__WIN32_NAME}/cmake")
               # use explicit path to avoid "surprises"
               if( IS_DIRECTORY "${_TMP_DLFCN__WIN32_DIR}")
                  list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_DLFCN__WIN32_DIR}")
                  # we only want top level INHERIT_OBJC_DEPS, so disable them
                  if( NOT NO_INHERIT_OBJC_DEPS)
                     set( NO_INHERIT_OBJC_DEPS OFF)
                  endif()
                  list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
                  set( NO_INHERIT_OBJC_DEPS ON)
                  #
                  include( "${_TMP_DLFCN__WIN32_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
                  #
                  list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
                  list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
                  list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_DLFCN__WIN32_DIR}")
                  #
                  unset( DLFCN__WIN32_DEFINITIONS)
                  unset( DLFCN__WIN32_RENDEZVOUS_GLOBALS)
                  include( "${_TMP_DLFCN__WIN32_DIR}/Definitions.cmake" OPTIONAL)
                  list( APPEND INHERITED_DEFINITIONS ${DLFCN__WIN32_DEFINITIONS})
                  include( "${_TMP_DLFCN__WIN32_DIR}/Definitions.cmake" OPTIONAL)
                  list( APPEND RENDEZVOUS_GLOBALS ${DLFCN__WIN32_RENDEZVOUS_GLOBALS})
                  break()
               else()
                  message( STATUS "${_TMP_DLFCN__WIN32_DIR} not found")
               endif()
            endforeach()
      else()
         # Disable with: `mulle-sourcetree mark dlfcn-win32 no-require-link`
         message( SEND_ERROR "DLFCN__WIN32_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-core
${MULLE_PREFERRED_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}dl${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}dl${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}dl${MULLE_FALLBACK_LIBRARY_SUFFIX}
dl")
      endif()
   endif()
endif()
