#
# cmake/reflect/_Libraries.cmake is generated by `mulle-sde reflect`. Edits will be lost.
# Disable generation of this file with:
#   mulle-sde environment  --global set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE

if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: dl;no-all-load,no-cmakeinherit,no-import,no-os-mingw,no-os-windows,no-share;dl,dlfcn
# Disable with: `mulle-sourcetree mark dl no-link`
#
if( NOT (${CMAKE_SYSTEM_NAME} MATCHES "Windows" OR ${CMAKE_SYSTEM_NAME} MATCHES "Windows"))
   if( NOT DL_LIBRARY)
      find_library( DL_LIBRARY NAMES dl dlfcn)
      message( STATUS "DL_LIBRARY is ${DL_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( DL_LIBRARY)
         #
         # Add DL_LIBRARY to OS_SPECIFIC_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark dl no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${DL_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( FATAL_ERROR "DL_LIBRARY was not found")
      endif()
   endif()
endif()


#
# Generated from sourcetree: psapi;no-all-load,no-cmakeinherit,no-import,no-public,no-require,only-os-mingw,only-os-windows;
# Disable with: `mulle-sourcetree mark psapi no-link`
#
if( ${CMAKE_SYSTEM_NAME} MATCHES "Windows" OR ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( NOT PSAPI_LIBRARY)
      find_library( PSAPI_LIBRARY NAMES psapi)
      message( STATUS "PSAPI_LIBRARY is ${PSAPI_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( PSAPI_LIBRARY)
         #
         # Add PSAPI_LIBRARY to OS_SPECIFIC_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark psapi no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${PSAPI_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( STATUS "PSAPI_LIBRARY is missing but it is marked as \"no-require\"")
      endif()
   endif()
endif()
