/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_dlfcn_include_h__
#define _mulle_dlfcn_include_h__

// You can tweak the following #include with these commands.
// (Use 3035297A-114F-447F-AA5A-EDF4E3B174B6 instead of dl if there are duplicate entries)
//    remove:             `mulle-sourcetree mark dl no-header`
//    rename:             `mulle-sde dependency|library set dl include whatever.h`
//    reorder:            `mulle-sourcetree move dl <up|down>`
//    toggle #include:    `mulle-sourcetree mark dl [no-]import`
//    toggle public:      `mulle-sourcetree mark dl [no-]public`
//    toggle optional:    `mulle-sourcetree mark dl [no-]require`
//    remove for platform:`mulle-sourcetree mark dl no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
# if ! defined( _WIN32) && ! defined( __windows__)
# include <dlfcn.h>   // dl
#endif

#endif
