/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_dlfcn_include_private_h__
#define _mulle_dlfcn_include_private_h__

// How to tweak the following psapi #include
//    remove:          `mulle-sourcetree mark psapi no-header`
//    rename:          `mulle-sourcetree mark psapi set include whatever.h`
//    toggle public:   `mulle-sourcetree mark psapi [no-]public`
//    toggle optional: `mulle-sourcetree mark psapi [no-]require`
//    remove for os:   `mulle-sourcetree mark psapi no-os-<osname>`
# if defined( _WIN32) || defined( __windows__)
# ifdef __has_include
#  if __has_include(<psapi.h>)
#    include <psapi.h>   // psapi
#   define HAVE_LIB_PSAPI
#  endif
# endif
# endif

#endif
