/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _mulle_dlfcn_include_h__
#define _mulle_dlfcn_include_h__

// library: remove with `mark no-header`, rename with `set include`
# if defined( _WIN32)
#  include <dlfcn.h>   // dlfcn
# endif

// library: remove with `mark no-header`, rename with `set include`
# if ! defined( _WIN32)
#  include <dlfcn.h>   // dl
# endif

#endif
